### ISSUE TITLE
DSL methods not available when using Capybara and RSpec

### ISSUE THREAD

**Issue by suan** [donv/capybara-screenshot-diff#1]
Not sure if this is expected to work? But `Capybara::Screenshot::Diff` is defined for me, but the DSL methods such as `screenshot` are not. I am currently working in a fork to determine what exactly is wrong - I suspect they may need to be added to `Capybara::DSL`?

**Comment by donv** [comment]
Hi @suan !

Congratulations on filing Issue #1 !

When you include the gem in your Gemfile, Bundler will initiate it and the gem hooks itself into `ActionDispatch::IntegrationTest`, making the methods available.

Are you using `ActionDispatch::IntegrationTest` for your tests?

**Comment by suan** [comment]
I think I found the (should've been quite obvious) issue - I use RSpec, and
this gem is minitest-only :)

**Comment by donv** [comment]
😄   Yes, it is, but only because that is what I am using.  Would you like to help make it available for RSpec?  Should not be too much work.

**Comment by garmoshka-mo** [comment]
Solution for `rspec` is to add `include Capybara::Screenshot::Diff::TestMethods`: (Worth to mention it in docs)

```
require 'rails_helper'
require 'capybara/poltergeist'
Capybara.javascript_driver = :poltergeist

describe 'Permissions admin', :type => :feature, :js => true do

  include Capybara::Screenshot::Diff::TestMethods

  it 'works with permissions' do
    visit('/')
    screenshot 'home_page'
  end

end
```

**Comment by donv** [comment]
Hi!

I updated the README:

    https://github.com/donv/capybara-screenshot-diff#usage

Could you take a look and see if it explains your problem.

**Comment by donv** [comment]
Hi!

I updated the README:

    https://github.com/donv/capybara-screenshot-diff#usage

Could you take a look and see if it explains your problem.

**Comment by garmoshka-mo** [comment]
Hi, @donv ! Yep, that makes usage clear 👍
