### ISSUE TITLE
Screenshot of a specified element

### ISSUE THREAD

**Issue by ciembor** [donv/capybara-screenshot-diff#12]
It would be awesome if we could take a screenshot of only specified element. Like `canvas`. Testing canvas by checking diff in screenshot would be very reasonable.

**Comment by donv** [comment]
@ciembor Hi!

Do you think you could submit a PR for this?

**Comment by ciembor** [comment]
@donv Unfortunatelly currently I don't have time for this :(.

**Comment by donv** [comment]
No problem.  Maybe I'll do it if I get the need myself :)  Reopen if you need it.
