### ISSUE TITLE
Auto-switch driver

### ISSUE THREAD

**Issue by donv** [donv/capybara-screenshot-diff#17]
Hi @pftg !

I'd like to auto-switch the backend driver based on availability of gens and libraries.

The driver config should allow `:auto` in addition to the current `:chunky_png` and `:vip`.

If `:auto` is selected, and it should be the default, we should try to select chunky_png if the chunky_png gem is available or VIP if the VIP gem is avalable.

If neither chunky_png nor VIP is available, we should fail with a USAGE message stating that either chunky_png or VIP is required.

If an actual driver is selected by the developer, we should not fall back to another driver, but fail if it is not present or has trouble loading.

With this function, neither chunky_png nor VIP should be an install requirement for the gem directly, although one of them will be needed for proper function.

@pftg Are you up for implementing this?  With this in place, I'd like to push a new release.

**Comment by pftg** [comment]
@donv start working on this

**Comment by pftg** [comment]
@donv please check #18
