### ISSUE TITLE
Compare without annotations for quick equal

### ISSUE THREAD

**Issue by pftg** [donv/capybara-screenshot-diff#35]
In order to take a stable screenshot, we compare several shots and as soon we confirm that shots are stable, that there are no changes between them then we start the comparison with annotations enabled.

There is an idea to improve the current `quick_equal`:

Build checksum for the image with filters enabled and without. Then compare only checksums previous with the current shot.
This reduces the time on loading the second image to confirm that images are different.

**Comment by donv** [comment]
Sounds good to me.

**Comment by donv** [comment]
Any takers for this?  We compare the file size before comparing pixels,  Comparing a checksum is better, but requires some implementation.  If anyone wants to submit a PR, I welcome it.  If not I will close this issue.

**Comment by pftg** [comment]
@donv let's close for now, when I'll have time to refactor that part I'll create PR
