### ISSUE TITLE
Feature Request: I want to easily see the areas of the screenshot that are different

### ISSUE THREAD

**Issue by asavageiv** [donv/capybara-screenshot-diff#43]
First off, thank you so much for making this gem. It is very useful.

When I worked at Google we had a similar tool. It had a useful feature that overlayed the two screenshots on top of each other making the top one slightly transparent so you could see where the diffs were.

It could also highlight diff areas with a semi-transparent rectangle, making them easier to spot.

Either of both of these two features would make comparing different screenshots much easier.

**Comment by pftg** [comment]
Just want to confirm that you know that there is a pretty close similar solution here. You can find a comparison image near the screenshots with the suffix `.commited.png` in the name, and you will get such result:
![email_error committed](https://user-images.githubusercontent.com/125715/167177871-d15b2455-2633-4284-8e4f-1fb0278ddcff.png)

Or do you still prefer to have an "overlayed" solution?

**Comment by asavageiv** [comment]
Ah, I see. That is pretty good! 

At Google the tool wrapping the screenshot differ was pretty sophisticated. It had a webpage UI with buttons that would let you compare side-by-side, flip between the images, or overlay them. Maybe that is out of scope of this project, but it was really useful to have all of them!

**Comment by pftg** [comment]
Yep, such services like https://docs.percy.io/docs/capybara and https://ghostinspector.com/ provide much richer UI. This is small gem just to give basic functionality

**Comment by donv** [comment]
@asavageiv Is the current red rectangle outline sufficient?  If so, we can close this issue 😄

**Comment by asavageiv** [comment]
Yes, it's sufficient. Image magick also has good diff generation to be used.

**Comment by donv** [comment]
👍
