### ISSUE TITLE
Allow to skip area or crop by css selectors

### ISSUE THREAD

**Issue by pftg** [donv/capybara-screenshot-diff#46]
Will be great to provide CSS selectors which should be excluded from the comparison, or selectors for containers to crop. 

We can do this as separate libs or helpers. Also will be great to provide them as default, in order to skip footers and navigations and compare only the content part.

**Comment by donv** [comment]
We added the `crop` option which I feel is a more versatile and useful option than a selector, especially since the step from selector to coordinates involves javascript execution.

However, I will support a pull request for this 😄 👍
