### ISSUE TITLE
How do you assert image difference

### ISSUE THREAD

**Issue by HugApps** [donv/capybara-screenshot-diff#5]
I followed the read me , but it does not explain how to actually check the image differences . In my rspec script, I called screenshot 'test.png' , it creates a screen shot just fine, but when I switch CSS and color and re run , it does not detect changes

**Comment by donv** [comment]
Hi!

Thanks for the report!  The screen shot is checked against the previously **committed** version, so you need to commit the previous version to get a diff.  The diff is then stored alongside the original with a `~` at the end, and the test output indicates this by logging the full path of the new and old version of the screen shot.

I hope this helps.  😄

**Comment by donv** [comment]
I added a section in the README for this:

    Screen shots are compared to the previously COMMITTED version of the same screen shot.
