### ISSUE TITLE
Add Support for Capybara 3.0

### ISSUE THREAD

**Issue by Donhomerj** [donv/capybara-screenshot-diff#7]
Hi, 
I would like to use this project with a newer version of Capybara (3.0.2). Is it possible to test it with 3.0.2 and change the dependency? 

Thank you!

**Comment by donv** [comment]
I can definitely look into that.  I think the dependency will be '~> 3.0'.

Would you like to make a PR with the dependency change and change to the .travis file?  

If not, I'll do a quick commit right away.

**Comment by donv** [comment]
@Donhomerj I have loosened the dependency so you should now be able to try the gem with Capybara 3.x by including the gem directly from github:

```ruby
git_source(:github) { |repo_name| "https://github.com/#{repo_name}.git" }
gem 'capybara-screenshot-diff', github: 'donv/capybara-screenshot-diff'
```

Let me know how it goes.  I will not be able to test much myself until `minitest-capybara-rails` and others upgrade.

**Comment by Donhomerj** [comment]
I wanted to push but git tells me I dont have any permission. I am quite new and I might do something wrong here. I will test your changes, thank you!

**Comment by Donhomerj** [comment]
@donv unfortunately I could not get it to work, but it might be my environment. I am using cucumber with capybara and selenium. After requiring 'capybara/screenshot/diff' and including the module, the method screenshot is not available.

**Comment by donv** [comment]
We have setup for minitest and rspec, so adding a setup for cucumber should not be difficult.  Are you trying to use screenshot in a step definition?

Do you have a project on GitHub I can try it with?

**Comment by Donhomerj** [comment]
I am afraid I cannot share the project, but if you still have a possibility to test it, that would be awesome!
I want to take screenshots in my ruby code. Something like: 
`new_screenshot = screenshot`
`expect(old_screenshot).to eq(new_screenshot)`

Thank you for your help!

**Comment by Donhomerj** [comment]
If that would help, I could create a small cucumber project tomorrow

**Comment by donv** [comment]
I will gladly add cucumber support to the gem if you come up with how to do it.  I can however not spend any time on researching it myself.

**Comment by donv** [comment]
This gem now supports capybara 3.x.
