### ISSUE TITLE
Crop is wrong by a factor of 2

### ISSUE THREAD

**Issue by phikes** [donv/capybara-screenshot-diff#75]
I am using your library on an iMac and suspect that the screen pixel density somehow is not taken into account when using the crop option. I am using vips as a driver.

This doesn't work:
```
screenshot "test", crop: '#my_element', driver: :vips
```

This works:
```
my_element.evaluate_script("this.getBoundingClientRect()").symbolize_keys => {left:, top:, right:, bottom:, width:, height:}
screenshot "test", crop: [left * 2, top * 2, right * 2, bottom * 2]
```

If you point me in the right direction I can prepare a PR to fix this. From what I understand you always take a "fullscreen" screenshot and then crop afterwards using the driver. In that case I suppose it is the driver crop call which needs to take this into account. I wouldn't really fiddle with determining the pixel density but rather offload this to the driver. However I wasn't able to find anything related to that in the vips docs.

The other option I can imagine is that the screenshot is taken at "normal" pixel density but vips crops it using the screen pixel density.

Let me know how I can be of help.

**Comment by phikes** [comment]
Actually I just discovered this: https://github.com/donv/capybara-screenshot-diff/blob/c637b6d48253a9f26e80f8e584f8e9a92dc53344/lib/capybara/screenshot/diff/screenshoter.rb#L68C19-L68C19

Looks like this is not necessary anymore and messing with cropping.

**Comment by pftg** [comment]
@phikes could you provide more details why it's redundant?

If you want to create PR, starting from a simple test case will be great.

There is an issue with Retina. We need to have a Retina device to run those tests. I can do it on my local machine, and we can ignore it for CI/CD.

**Comment by phikes** [comment]
I am on a retina mac but the resulting screenshot is incorrectly off by a factor of 2. This code seems to be executed on my machine so I suspect something else would already compensate for the retina screen (or crop never worked on machines with a higher pixel density). Maybe this happened with an update of a gem or something?

**Comment by phikes** [comment]
I tried using the github master version and it is still incorrect.

**Comment by pftg** [comment]
@phikes could you give me what screenshot you got and what is the expected one?

**Comment by pftg** [comment]
@phikes what chrome driver options have you set? Have you checked this notice:

> Halving retina screenshot.  You should add "force-device-scale-factor=1" to your Chrome chromeOptions args.

**Comment by phikes** [comment]
I will send you a screenshot as soon as I can, thank you for investigating. I do not have any option set by myself however am using Puffing Billy and am not sure what they set. I can debug this closer tomorrow. Thanks again!

**Comment by pftg** [comment]
Example how you can setup this
```ruby
  driven_by :selenium, using: ENV.fetch('DRIVER', :headless_chrome).to_sym, screen_size: [1024, 768] do |options|
    options.args << '--force-device-scale-factor=1'
  end
```

**Comment by phikes** [comment]
Thanks. I am trying it at this very moment. The following are the screenshots of actual and expected:
![shift_actual](https://github.com/donv/capybara-screenshot-diff/assets/3684890/7f796713-37c0-46a8-a937-97cadd009793)
![shift](https://github.com/donv/capybara-screenshot-diff/assets/3684890/d5d07baf-9302-4b89-b841-bfa1106467eb)

Generated using the following code:
```
    expect(page).to have_text "10:00 - 18:00"
    all(".fc-scroller").last.scroll_to all(".fc-event-main").first
    all(".fc-event-main").first.evaluate_script("this.getBoundingClientRect()").symbolize_keys => {left:, top:, right:, bottom:, width:, height:}

    # screenshot :shift, crop: '.fc-event-main'
    screenshot :shift, crop: [left * 2, top * 2, right * 2, bottom * 2]
```

**Comment by phikes** [comment]
> Example how you can setup this
> 
> ```ruby
>   driven_by :selenium, using: ENV.fetch('DRIVER', :headless_chrome).to_sym, screen_size: [1024, 768] do |options|
>     options.args << '--force-device-scale-factor=1'
>   end
> ```

This works, however I had to switch drivers temporarily because the puffing billy driver doesn't call the block at all. But that shouldn't be your problem.

Where exactly did you copy this from?

> @phikes what chrome driver options have you set? Have you checked this notice:
> 
> > Halving retina screenshot.  You should add "force-device-scale-factor=1" to your Chrome chromeOptions args.

I hope I didn't miss anything in your docs?

Anyways what is left here to do? Should I open a PR for adding this to the README?

**Comment by pftg** [comment]
@phikes, this message is in https://github.com/donv/capybara-screenshot-diff/blob/66cab689e7402d19be3a20e5ab110dff3f0750c5/lib/capybara/screenshot/diff/screenshoter.rb#L96.

I always forget about it. It will be great to get PR with updated README and code examples how to do this.

**Comment by phikes** [comment]
Ok, I didn't see this output. I suppose it is not present in the gem version? Will prepare something quickly. Thank you for your ambitious help with this!

**Comment by phikes** [comment]
Closing this now that the PR is open at #79.
