### ISSUE TITLE
Image Minification

### ISSUE THREAD

**Issue by mikefogg** [donv/capybara-screenshot-diff#8]
Hey @donv back at it with this thing :) You'd mentioned you used this for your company and personal projects. I was curious if you'd run into any situations where you'd want to minify the png's before comparing them to limit the file-size stored in the git repo?

I was thinking of some sort of `minify: true` config, since it does (obviously) add a delay while the images are optimized. Potentially using something like `https://github.com/toy/image_optim` can shrink the file-sizes down a lot (> 50% in some cases). What do you think?

**Comment by donv** [comment]
Hi @mikefogg !

Have you been using the gem?  Let me know if there is any trouble.

Minifying the images sounds like a good feature.  Would you use it if it existed?  I ask to avoid adding features nobody will use 😄 .

What size would you minify to?  I guess that should be an option:

```ruby
Capybara::Screenshot.window_size = [1024, 768]
Capybara::Screenshot.resize_to = [320, 240]
```

ChunkyPNG is already a dependency so we will use that to resize the image.

What do you think?  Would you like to submit a PR?

**Comment by donv** [comment]
OK, I just read your proposition properly.  "Minify", not "resize".

Still a good feature:

```ruby
Capybara::Screenshot.minify = true
```

using https://github.com/toy/image_optim

Would you like to submit a PR?

**Comment by mikefogg** [comment]
@donv Sure! I'll take a swing at getting that added in there this week. I think it will be a great feature for those storing files in their git repo (since the files can get pretty big).

**Comment by donv** [comment]
Hi @mikefogg !

How is this coming along?

**Comment by donv** [comment]
@mikefogg Any chance for completing this?

**Comment by donv** [comment]
@mikefogg have you given this any more thought?

**Comment by pftg** [comment]
@donv what do you think to store comparisons in WEBP format as an option, this will reduce the size of the image without losing quality.

But the best way is just to resize to the smallest possible window size, which definitely reduces image size.

**Comment by donv** [comment]
I like all ideas that improve performance and reduce storage size  :)

A PR is very welcome.

Reducing the window size is up to the individual project, right?

**Comment by donv** [comment]
Closing this since @mikefogg is not responding.  Please reopen if needed.

**Comment by mikefogg** [comment]
Ugh, @donv so sorry! I ended up moving away from using this gem since most of my work in the past couple of years have had separate frontend framework sites that use Jest for the testing framework.

**Comment by donv** [comment]
@mikefogg No worries.  Life happens 😄 .
