### ISSUE TITLE
skip_area with CSS selector not covering full area with vips driver

### ISSUE THREAD

**Issue by alan-pie** [donv/capybara-screenshot-diff#87]
I'm using `skip_area: [". admin-order-qr-code"]` to generate the screnshots below. As you can see from the diff files, the skip area is missing the bottom part of the QR code. The gist has the HTML + CSS and using Chrome's inspect tool I can see that the QR Code is fully contained within its parent, so it's not an overflow issue. Furthermore, if I switch to chunky_png instead of VIPS then no diff is detected.

https://gist.github.com/alan-pie/86ac2d3c90e46032d7325c439b01bf1e

![00_loaded base diff](https://github.com/donv/capybara-screenshot-diff/assets/65185890/c3ddeb75-f51a-4624-8686-8d4e35c18b45)
![00_loaded diff](https://github.com/donv/capybara-screenshot-diff/assets/65185890/9a42a463-f42b-4185-ba02-eb20c394b5bb)
![00_loaded](https://github.com/donv/capybara-screenshot-diff/assets/65185890/76a9423c-987e-4a84-865b-58bc2e35d2f2)

**Comment by pftg** [comment]
Thanks @alan-pie will check on weekend

**Comment by alan-pie** [comment]
Adding 1 to the height in `add_black_box` causes the test to pass.

```
          def add_black_box(memo, region)
            top, left, width, height = *region.to_top_left_corner_coordinates
            memo.draw_rect([0, 0, 0, 0], top, left, width, height + 1, fill: true)
          end
```

**Comment by alan-pie** [comment]
I think `BrowserHelpers.region_for` is doing a `to_i` that clips the region to be one pixel too small.
